spring:
  profiles:
    active: -dev
---
spring:
  profiles: dev        #开发环境     
  application:
    name: microservicecloud-config-jxk-dev
---
spring:
  profiles: test      #开发环境     
  application:
    name: microservicecloud-config-jxk-test
#  请保持UTF-8格式